name: CustomRecipe
main: com.gmail.uprial.customrecipe.CustomRecipe
version: 0.1.0
api-version: 1.14
commands:
   customrecipe:
      description: Reload CustomRecipe config
      usage: /customrecipe help
      permission:
      permission-message:
permissions:
  customrecipe.reload:
        description: Gives access to CustomRecipe 'reload' command
        default: op
